image: Visual Studio 2015
clone_depth: 5
platform: Any CPU
environment:
  github_token:
    secure: K71ovddtT7BuOR1D1K9uVRdOT2+Apl6GdQjBYjUki/ySUX9EcWb2MNtupx5ymrkt

configuration: Release

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

#init:
  # Set version number

before_build:
  - ps: .\Set-Version.ps1
  - cmd: nuget restore .\FooLib.sln -Verbosity detailed

build:
  parallel: false
  project: .\FooLib.sln
  verbosity: detailed

before_test:
  - ps: .\Prepare-TestEnvironment.ps1

test:
  assemblies:
    - '**\*.tests.dll'

cache:
  - packages -> **\packages.config

after_build:
  - ps: .\nuget\Pack.ps1

artifacts:
  - path: '.\nuget\artifacts\FooLib.dll.*.nupkg'
    name: nuget
    type: NuGetPackage

deploy:
  - provider: NuGet
    api_key:
      secure: LKL3BM5Iphp+fjoZzhqLAMrQOLrNXvY4tEEa5zRKpTY2Ti4gOzBUhxaprnCzfTO3
    skip_symbols: false
    artifact: /.*\.nupkg/
    on:
      DeployArtifacts: true
  - provider: GitHub
    description: 'Release'
    release: $(appveyor_build_version) #$(appveyor_repo_tag_name)
    auth_token:
      secure: K71ovddtT7BuOR1D1K9uVRdOT2+Apl6GdQjBYjUki/ySUX9EcWb2MNtupx5ymrkt
    artifact: /.*\.nupkg/
    on:
      DeployArtifacts: true

after_deploy:
    - ps: .\Update-VersionPostDeploy.ps1
    - git config --global credential.helper store
    - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:github_token):x-oauth-basic@github.com`n"
    - git config --global user.email "jasper-d@users.noreply.github.com"
    - git config --global user.name "jasperd"
    - git add --all
    - git commit --all -m "Update version file after deployment from CI server"
    - git push --repo origin